name: Build Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Puedes especificar una versión concreta si es necesario

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Clean previous builds
      run: |
        if (Test-Path dist) { Remove-Item -Recurse -Force dist }  # Elimina el directorio 'dist' solo si existe

    - name: Build Executable
      run: |
        pyinstaller --onefile --name TicketApp src/interfaz.py  # Verifica que la ruta de tu archivo .py sea correcta

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TicketApp
        path: dist/TicketApp.exe  # Ruta del ejecutable generado
